// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Para_DisableGuard","status":true,"description":"Makes it so the default title screen is skipped when booting up the game and after a gameover.","parameters":{}},
{"name":"ButtonPicture","status":true,"description":"Makes a picture clickable.","parameters":{}}
];
