// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"DoubleX RMMZ Enhanced Codebase","status":true,"description":"Versions: { codebase: \"1.1.1\", plugin: \"v0.00a\" }\r\nFixes bugs, improves codebase quality, boosts performance and gives new APIs","parameters":{"rngPartNum":"10"}},
{"name":"Para_DisableGuard","status":true,"description":"Makes it so the default title screen is skipped when booting up the game and after a gameover.","parameters":{}},
{"name":"ButtonPicture","status":true,"description":"Makes a picture clickable.","parameters":{}},
{"name":"DoubleX RMMZ State Triggers","status":true,"description":"Versions: { codebase: \"1.1.0\", plugin: \"v1.00b\" }\r\nLets you run some codes set by your notetags on some important state timings","parameters":{"addNotetagDataTypePriorities":"[\"thisState\"]","removeNotetagDataTypePriorities":"[\"thisState\"]","resetNotetagDataTypePriorities":"[\"thisState\"]","expireNotetagDataTypePriorities":"[\"thisState\"]","turnNotetagDataTypePriorities":"[\"thisState\"]"}},
{"name":"IconTurns","status":false,"description":"v1.04 Number of turns remaining for states/debuffs/buffs is\r\ndisplayed on the icon.\r\n<lolaccount DisplayStateTurnsOnIcon>","parameters":{"Font Size":"16","Position":"topright","---Compatibility---":"","Decimal Places":"0"}},
{"name":"CombatFunctions","status":true,"description":"Makes it so the default title screen is skipped when booting up the game and after a gameover.","parameters":{}},
{"name":"EventFunctions","status":true,"description":"Makes it so the default title screen is skipped when booting up the game and after a gameover.","parameters":{}}
];
